target("lib_SDL2")
    set_kind("phony")
    add_includedirs("src/include/", {public = true})
    add_headerfiles("src/**.h")
    add_linkdirs("src/lib/x64/", {public = true})
    add_links("SDL2", "SDL2main", "shell32", {public = true})
    add_ldflags("/SUBSYSTEM:CONSOLE", {public = true})
target_end()